"""Report generator: builds Markdown, HTML and PDF reports from simulation/policy data."""
import os
import datetime
import markdown2
from fpdf import FPDF
from typing import Dict, Any

REPORT_TEMPLATES = [
    "Executive Summary", "Climate Report", "Policy Report", "ESG Report",
    "Cost-Benefit Analysis", "Government Proposal", "University Report", "Research Summary",
]


def build_markdown(report_type: str, scenario: Dict[str, Any], policy: Dict[str, Any],
                    sim_summary: Dict[str, Any], agents: Any = None,
                    employment: Dict[str, Any] = None, economy: Dict[str, Any] = None,
                    citizen: Dict[str, Any] = None) -> str:
    date = datetime.datetime.utcnow().strftime("%Y-%m-%d")
    md = [f"# {report_type}: {scenario.get('name', 'ClimateVerse Scenario')}",
          f"*Generated by ClimateVerse on {date}*",
          "",
          "> **Disclaimer**: ClimateVerse demo simulations use transparent simplified models and "
          "synthetic (DEMO DATA) unless live datasets are configured. This is a decision-support "
          "prototype, not a certified scientific forecasting system.",
          "",
          "## 1. Scenario & Assumptions",
          f"- **City**: {scenario.get('city_name', 'Pune')} (DEMO DATA)",
          f"- **Goal**: {scenario.get('goal')}",
          f"- **Target**: {scenario.get('target_pct')}%",
          f"- **Budget**: ₹{scenario.get('budget_crore')} crore",
          f"- **Timeline**: {scenario.get('start_year')} - {scenario.get('end_year')}",
          "",
          "## 2. Selected Policy",
          f"**{policy.get('name', 'N/A')}**",
          f"{policy.get('description', '')}",
          "",
          "| Metric | Value |",
          "|---|---|",
          f"| Cost | ₹{policy.get('cost_crore', 0)} crore |",
          f"| CO2 Reduction | {policy.get('co2_reduction_pct', 0)}% |",
          f"| AQI Impact | -{policy.get('aqi_impact', 0)} points |",
          f"| Jobs Created | {policy.get('jobs_created', 0)} |",
          f"| ROI | {policy.get('roi_pct', 0)}% |",
          f"| Renewable Energy | {policy.get('renewable_pct', 0)}% |",
          f"| Green Cover | {policy.get('green_cover_pct', 0)}% |",
          f"| Citizen Acceptance | {policy.get('citizen_acceptance', 0)}% |",
          f"| Disaster Resilience | {policy.get('disaster_resilience', 0)}/100 |",
          "",
          "## 3. Simulation Results Summary",
          f"- Final year: {sim_summary.get('year')}",
          f"- CO2: {sim_summary.get('co2_mt')} Mt",
          f"- AQI: {sim_summary.get('aqi')}",
          f"- Temperature: {sim_summary.get('temperature_c')}°C",
          f"- Water availability: {sim_summary.get('water_availability_pct')}%",
          f"- Green cover: {sim_summary.get('green_cover_pct')}%",
          f"- Renewable energy: {sim_summary.get('renewable_pct')}%",
          f"- GDP: ${sim_summary.get('gdp_billion_usd')}B",
          f"- SDG Score: {sim_summary.get('sdg_score')}/100",
          "",
          ]

    if employment:
        md += ["## 4. Employment Impact",
               f"- Jobs lost: {employment.get('jobs_lost')}",
               f"- Jobs created: {employment.get('jobs_created')}",
               f"- Net employment: {employment.get('net_employment')}",
               ""]

    if economy:
        md += ["## 5. Economic Impact",
               f"- Final GDP: ${economy.get('final_gdp_billion_usd')}B",
               f"- Payback period: {economy.get('payback_years')} years",
               ""]

    if citizen and citizen.get("yearly"):
        last_c = citizen["yearly"][-1]
        md += ["## 6. Citizen Impact",
               f"- Public acceptance: {last_c.get('public_acceptance_pct')}%",
               f"- Happiness index: {last_c.get('happiness_index')}",
               f"- Health impact index: {last_c.get('health_impact_index')}",
               ""]

    if agents:
        md += ["## 7. AI Agent Recommendations"]
        for a in agents:
            md += [f"**{a['agent']}** (confidence {a['confidence']*100:.0f}%): {a['recommendation']}"]
        md += [""]

    md += ["## Limitations",
           "This report is generated from a simplified simulation model using synthetic demo data "
           "for Pune. Formulas are transparent and documented but not scientifically validated "
           "forecasts. Results should be treated as illustrative decision-support, not certified "
           "climate projections.",
           ""]

    return "\n".join(md)


def save_report(content_md: str, out_dir: str, report_id: str, fmt: str = "markdown") -> str:
    os.makedirs(out_dir, exist_ok=True)
    if fmt == "markdown":
        path = os.path.join(out_dir, f"{report_id}.md")
        with open(path, "w") as f:
            f.write(content_md)
        return path
    elif fmt == "html":
        html_body = markdown2.markdown(content_md, extras=["tables"])
        html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>ClimateVerse Report</title>
<style>
body {{ font-family: -apple-system, Arial, sans-serif; max-width: 860px; margin: 40px auto; padding: 0 20px; color:#1a2e22; }}
h1 {{ color: #0f5132; }} h2 {{ color: #14532d; border-bottom: 2px solid #d1fae5; padding-bottom:4px;}}
table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
td, th {{ border: 1px solid #d1d5db; padding: 8px 12px; text-align:left; }}
blockquote {{ background:#fef9c3; border-left:4px solid #eab308; padding:10px 16px; }}
</style></head><body>{html_body}</body></html>"""
        path = os.path.join(out_dir, f"{report_id}.html")
        with open(path, "w") as f:
            f.write(html)
        return path
    elif fmt == "pdf":
        import textwrap
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_left_margin(15)
        pdf.set_right_margin(15)
        pdf.set_font("Helvetica", size=11)
        for line in content_md.splitlines():
            clean = line.replace("#", "").replace("*", "").replace("|", " ").replace("₹", "Rs.").strip()
            clean = clean.encode("latin-1", "replace").decode("latin-1")
            if not clean:
                pdf.ln(3)
                continue
            # Hard-wrap very long unbroken tokens (e.g. long words) to avoid FPDF width errors
            wrapped = textwrap.fill(clean, width=95, break_long_words=True, break_on_hyphens=False)
            for wline in wrapped.splitlines():
                pdf.set_x(pdf.l_margin)
                try:
                    pdf.multi_cell(0, 6, wline if wline else " ")
                except Exception:
                    pdf.set_x(pdf.l_margin)
                    pdf.multi_cell(0, 6, "[line omitted]")
        path = os.path.join(out_dir, f"{report_id}.pdf")
        pdf.output(path)
        return path
    else:
        raise ValueError("Unsupported format")
